### ISSUE TITLE
`download_and_extract` within `prepare_rirs.py` fails to detect metu/arni files

### ISSUE THREAD

**Issue by ChrisIck** [iranroman/SpatialScaper#67]
When re-running `prepare_rirs.py`, `download_and_extract` checks for existing files based on the download URL. However, since the metu/arni databases are renamed, they will always be downloaded/re-extracted. Checks should be done on the target names rather than the renamed files in `prepare_arni` and `prepare_metu`, this is likely leftover from the way it was set up with the TAU databases.

**Comment by iranroman** [comment]
Hello, I don't see this issue. There is no renaming in the current version of the library. 

For METU, the zip path is `SpatialScaper/datasets/rir_datasets/spargair.zip` and after being uncompressed its contents are in the directory `SpatialScaper/datasets/rir_datasets/spargair`.

For ARNI, the zip paths are `datasets/rir_datasets/source_data/6dof_SRIRs_eigenmike_raw.zip` and `datasets/rir_datasets/source_data/6dof_SRIRs_eigenmike_raw` for em32 `datasets/rir_datasets/source_data/6dof_SRIRs_eigenmike_SH.zip` and `datasets/rir_datasets/source_data/6dof_SRIRs_eigenmike_SH` for FOA.

`download_and_extract` checks for either, zip or uncompressed directory, to avoid the re-download (or re-extraction).

Let me know if there are specific steps I need to follow to reproduce your observation. I'll close this issue otherwise.
